apiVersion: v1
kind: Pod
metadata:
  name: k8s-java-app
  labels:
    app: k8s-java-app
spec:
  containers:
  - name: k8s-java-app
    image: ##DOCKER_PREFIX##/k8s-java-app
    ports:
    - containerPort: 8080
      name: app-port
    env:
    - name: SPRING_APPLICATION_JSON
      valueFrom:
        secretKeyRef:
          name: k8s-java-db-secret
          key: spring_application_json
    - name: JDBC_URL
      valueFrom:
        secretKeyRef:
          name: k8s-java-db-secret
          key: jdbc_url          
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: k8s-java-db-secret
          key: db_user
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: k8s-java-db-secret
          key: db_password
  imagePullSecrets:
  - name: ocirsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-java-app-service
spec:
  selector:
    app: k8s-java-app
  ports:
  - name: http-service-port
    protocol: TCP
    port: 80
    targetPort: app-port
---