apiVersion: v1
kind: Pod
metadata:
  name: k8s-node-ui
  labels:
    app: k8s-node-ui
spec:
  containers:
  - name: k8s-node-ui
    image: ##DOCKER_PREFIX##/k8s-node-ui:latest
    ports:
      - containerPort: 80
        name: http-port
  imagePullSecrets:
  - name: ocirsecret        
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-node-ui-service
spec:
  selector:
    app: k8s-node-ui
  ports:
  - name: http-service-port
    protocol: TCP
    port: 80
    targetPort: http-port
---    